version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /dashboard
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /examples/echo-service
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
